### ISSUE TITLE
[GUI] After successfull registration & verification of user's face, add a pop up window with last photo

### ISSUE THREAD

**Issue by emanuelkrzyszton** [davidgmorais/mais#7]
After successfull registration & verification of user's face, add a pop up window in which the last picture from database and the name of registered and authenticated user will appear in this confirmation window.

**Comment by davidgmorais** [comment]
An alternative approach than the one suggested was implemented in commit e63ffc3bc02231a0aa19fc8b1faac1a2529e4677, where user feedback is given using popups and some sleep frames were used to show the camera feedback at the beginning of the face authentication process (instead of starting capturing frames right away)
